# Simple Makefile.w32 for stunnel.exe by Michal Trojnara 1998-1999

SSLDIR=../openssl-0.9.4

CC=gcc
CFLAGS=-O2 -Wall -DUSE_WIN32 -DHAVE_OPENSSL -I$(SSLDIR)/outinc
LDFLAGS=-s
# LIBS=-L$(SSLDIR)/out -lssl -lcrypto -lwsock32 -lgdi32
LIBS=-L$(SSLDIR)/out -leay32 -lssl32 -lwsock32 -lgdi32
OBJS=stunnel.o ssl.o protocol.o sthreads.o log.o

stunnel.exe: $(OBJS)
	$(CC) $(LDFLAGS) -o stunnel.exe $(OBJS) $(LIBS)

clean:
	del *.o
