.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH STUNNEL.OUT 1 " " "23/Dec/2001" " "
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
stunnel \- universal SSL tunnel
.SH "SYNOPSIS"
\fBstunnel\fR [\-c\ |\ \-T] [\-D\ [facility.]level] [\-O
a|l|r:option=value[:value]] [\-o\ file] [\-C\ cipherlist] [\-p
pemfile] [\-v\ level] [\-A\ certfile] [\-S\ sources] [\-a
directory] [\-t\ timeout] [\-u\ ident_username] [\-s\ setuid_user]
[\-g\ setgid_group] [\-n\ protocol] [\-P\ {\ dir/\ |\ filename\ |\ none\ }
] [\-B\ bytes] [\-R\ randfile] [\-W] [\-E\ socket] [\-I\ host]
[\-d\ [host:]port\ [\-f]\ ] [\ \-r\ [host:]port\ |\ {\ \-l\ |\ \-L\ }\ program\ [--
progname\ args]\ ]
.SH "DESCRIPTION"
The \fBstunnel\fR program is designed to work as \fISSL\fR encryption
wrapper between remote clients and local (\fIinetd\fR\-startable) or
remote servers. The concept is that having non-SSL aware daemons
running on your system you can easily set them up to communicate with
clients over secure SSL channels.
.PP
\fBstunnel\fR can be used to add SSL functionality to commonly used
\fIinetd\fR daemons like POP\-2, POP\-3, and IMAP servers, to standalone
daemons like NNTP, SMTP and HTTP, and in tunneling PPP over network
sockets without changes to the source code.
.PP
This product includes cryptographic software written by Eric Young
(eay@cryptsoft.com)
.SH "OPTIONS"
.Ip "\fB\-h\fR" 4
Print stunnel help menu
.Ip "\fB\-V\fR" 4
Print stunnel version and compile time defaults
.Ip "\fB\-D\fR level" 4
Debugging level
.Sp
Level is a one of the syslog level names or numbers emerg (0), alert
(1), crit (2), err (3), warning (4), notice (5), info (6), or debug
(7).  All logs for the specified level and all levels numerically less
than it will be shown.  Use \-D debug or \-D 7 for greatest debugging
output.  The default is notice (5).
.Sp
The syslog facility \*(L'daemon\*(R' will be used unless a facility name is
supplied.  (Facilities are not supported on windows.)
.Sp
Case is ignored for both facilities and levels.
.Ip "\fB\-O\fR a|l|r:option=value[:value]" 4
Set an option on accept/local/remote socket
.Sp
The values for linger option are l_onof:l_linger. The values for time
are tv_sec:tv_usec.
.Sp
\fBExamples:\fR
.Sp
\fB\-O l:\s-1SO_LINGER\s0=1:60\fR \- set one minute timeout for closing local
socket
.Sp
\fB\-O r:\s-1TCP_NODELAY\s0=1\fR \- turn off the Nagle algorithm for remote
sockets
.Sp
\fB\-O r:\s-1SO_OOBINLINE\s0=1\fR \- place out-of-band data directly into the
receive data stream for remote sockets
.Sp
\fB\-O a:\s-1SO_REUSEADDR\s0=0\fR \- disable address reuse (enabled by default)
.Sp
\fB\-O a:\s-1SO_BINDTODEVICE\s0=lo\fR \- only accept connections on loopback
interface
.Sp
See \*(L'stunnel \-V\*(R' for options supported on your system and their
default values.
.Ip "\fB\-o\fR file" 4
Append log messages to a file.
.Ip "\fB\-C\fR cipherlist" 4
Select permitted \s-1SSL\s0 ciphers
.Sp
A colon delimited list of the ciphers to allow in the \s-1SSL\s0 connection.
For example \s-1DES\s0\-\s-1CBC3-SHA:IDEA\s0\-\s-1CBC\s0\-\s-1MD5\s0
.Ip "\fB\-c\fR" 4
client mode (remote service uses \s-1SSL\s0)
.Sp
default: server mode
.Ip "\fB\-T\fR" 4
transparent proxy mode
.Sp
Re-write address to appear as if wrapped daemon is connecting from the
\s-1SSL\s0 client machine instead of the machine running stunnel. Available
only on some operating systems (Linux only, we believe) and then only
in server mode. Note that this option will not combine with proxy mode
(\-r) unless the client's default route to the target machine lies
through the host running stunnel, which cannot be localhost.
.Ip "\fB\-p\fR pemfile" 4
private key and certificate chain \s-1PEM\s0 file name
.Sp
A \s-1PEM\s0 is always needed in server mode (see \fIstunnel \-V\fR output for
default). Specifying this flag in client mode will use this key and
certificate chain as a client side certificate chain.  Using client
side certs is optional. The certificates must be in \s-1PEM\s0 format and
must be sorted starting with the certificate to the highest level
(root \s-1CA\s0).
.Ip "\fB\-v\fR level" 4
verify peer certificate
.Ip "\(bu" 12
level 1 \- verify peer certificate if present
.Ip "\(bu" 12
level 2 \- verify peer certificate
.Ip "\(bu" 12
level 3 \- verify peer with locally installed certificate
.Ip "\(bu" 12
default \- no verify
.Ip "\fB\-a\fR directory" 4
client certificate directory
.Sp
This is the directory in which stunnel will look for certificates when
using the \fI\-v\fR options. Note that the certificates in this directory
should be named \s-1XXXXXXXX\s0.0 where \s-1XXXXXXXX\s0 is the hash value of the
cert. This directory will override the stunnel compile-time default,
if any.
.Sp
See \fIstunnel \-V\fR output for default.
.Ip "\fB\-A\fR certfile" 4
Certificate Authority file
.Sp
This file contains multiple \s-1CA\s0 certificates, used with the \fI\-v\fR
options. This file will override the stunnel compile-time default, if
any.
.Sp
See \fIstunnel \-V\fR output for default.
.Ip "\fB\-S\fR sources" 4
Certificate source defaults
.Sp
Both stunnel and the \s-1SSL\s0 library used to compile stunnel have default
locations to look for your certificate file (\fI\-A\fR option) and
certificate directories (\fI\-a\fR option).  The \fB\-S\fR flag allows you to
control which of these default sources, if any, should be used.
.Sp
.Vb 4
\&    0 = ignore all default sources
\&    1 = use ssl library defaults
\&    2 = use stunnel defaults
\&    3 = use both ssl library and stunnel defaults
.Ve
(See \fIstunnel \-V\fR output for the default.)
.Sp
Note that the \fI\-A\fR and \fB\-a\fR flags overwrite, not supplement, the
stunnel defaults, whereas the ssl library defaults, if enabled, are
used in addition to the other sources.
.Sp
In general, to avoid hurting one's brain, use \fI\-S 0\fR and explicitly
set \fI\-A\fR and/or \fB\-a\fR as desired.
.Ip "\fB\-t\fR timeout" 4
session cache timeout
.Sp
default: 300 seconds.
.Ip "\fB\-N\fR servicename" 4
Service name to use for tcpwrappers. If not specified then a
tcpwrapper service name will be generated automatically for you. This
will also be used when auto-generating pid filenames.
.Ip "\fB\-u\fR ident_username" 4
Use \s-1IDENT\s0 (\s-1RFC\s0 1413) username checking
.Ip "\fB\-n\fR proto" 4
Negotiate \s-1SSL\s0 with specified protocol
.Sp
currently supported: smtp, pop3, nntp
.Ip "\fB\-E\fR socket" 4
Entropy Gathering Daemon socket to use to feed OpenSSL random number
generator.  (Available only if compiled with OpenSSL 0.9.5a or higher)
.Ip "\fB\-R\fR filename" 4
File containing random input.  The \s-1SSL\s0 library will use data from this
file first to seed the random number generator.
.Ip "\fB\-W\fR" 4
Do not overwrite the random seed files with new random data.
.Ip "\fB\-B\fR bytes" 4
Number of bytes of data read from random seed files.  With \s-1SSL\s0
versions less than 0.9.5a, also determines how many bytes of data are
considered sufficient to seed the \s-1PRNG\s0.  More recent OpenSSL versions
have a builtin function to determine when sufficient randomness is
available.
.Ip "\fB\-I\fR host" 4
\s-1IP\s0 of the outgoing interface is used as source for remote connections.
Use this option to bind a static local \s-1IP\s0 address, instead.
.Ip "\fB\-d\fR [host:]port" 4
daemon mode
.Sp
Listen for connections on [host:]port. If no host specified, defaults
to all \s-1IP\s0 addresses for the local host.
.Sp
default: inetd mode
.Ip "\fB\-f\fR" 4
foreground mode
.Sp
Stay in foreground (don't fork) and log to stderr instead of via
syslog (unless \-o is specified).
.Sp
default: background in daemon mode
.Ip "\fB\-l\fR program [-- programname [arg1 arg2 arg3...]  ]" 4
execute local inetd-type program.
.Ip "\fB\-L\fR program [-- programname [arg1 arg2 arg3...]  ]" 4
open local pty and execute program.
.Ip "\fB\-s\fR username" 4
\fIsetuid()\fR to username in daemon mode
.Ip "\fB\-g\fR groupname" 4
\fIsetgid()\fR to groupname in daemon mode. Clears all other groups.
.Ip "\fB\-P\fR { dir/ | file | none }" 4
Pid file location
.Sp
If the argument is a pathname ending in a slash, then a pid file named
\*(L"\fIstunnel.\fRservicename\fB.pid\fR\*(R" will be created in the specified
directory.  If the argument is a filename (no trailing slash), then
that filename will be used for the pid. If the argument is \*(L'none\*(R',
then no pid file will be created.
.Ip "\fB\-r\fR [host:]port" 4
connect to remote service
.Sp
If no host specified, defaults to localhost.
.SH "EXAMPLES"
In order to provide SSL encapsulation to your local \fIimapd\fR service,
use
.PP
.Vb 1
\&  stunnel -d 993 -l /usr/sbin/imapd -- imapd
.Ve
If you want to provide tunneling to your \fIpppd\fR daemon on port 2020,
use something like
.PP
.Vb 1
\&  stunnel -d 2020 -L /usr/sbin/pppd -- pppd local
.Ve
.SH "CERTIFICATES"
Each SSL enabled daemon needs to present a valid X.509 certificate to
the peer. It also needs a private key to decrypt the incoming data.
The easiest way to obtain a certificate and a key is to generate them
with the free \fIopenssl\fR package. You can find more information on
certificates generation on pages listed below.
.PP
Two things are important when generating certificate-key pairs for
\fBstunnel\fR. The private key cannot be encrypted, because the server
has no way to obtain the password from the user. To produce an
unencrypted key add the \fI\-nodes\fR option when running the \fBreq\fR
command from the \fIopenssl\fR kit.
.PP
The order of contents of the \fI.pem\fR file is also important. It should
contain the unencrypted private key first, then a signed certificate
(not certificate request). There should be also empty lines after
certificate and private key. Plaintext certificate information
appended on the top of generated certificate should be discarded. So
the file should look like this:
.PP
.Vb 8
\&  -----BEGIN RSA PRIVATE KEY-----
\&  [encoded key]
\&  -----END RSA PRIVATE KEY-----
\&  [empty line]
\&  -----BEGIN CERTIFICATE-----
\&  [encoded certificate]
\&  -----END CERTIFICATE-----
\&  [empty line]
.Ve
.SH "RANDOMNESS"
\fIstunnel\fR needs to seed the PRNG (pseudo random number generator) in
order for SSL to use good randomness.  The following sources are
loaded in order until sufficient random data has been gathered:
.Ip "\(bu" 4
The file specified with the \fI\-R\fR flag.
.Ip "\(bu" 4
The file specified by the \s-1RANDFILE\s0 environment variable, if set.
.Ip "\(bu" 4
The file .rnd in your home directory, if \s-1RANDFILE\s0 not set.
.Ip "\(bu" 4
The file specified with \*(L'--with-random\*(R' at compile time.
.Ip "\(bu" 4
The contents of the screen if running on Windows.
.Ip "\(bu" 4
The egd socket specified with the \fI\-E\fR flag.
.Ip "\(bu" 4
The egd socket specified with \*(L'--with-egd-sock\*(R' at compile time.
.Ip "\(bu" 4
The /dev/urandom device.
.PP
With recent (>=OpenSSL 0.9.5a) version of \s-1SSL\s0 it will stop loading
random data automatically when sufficient entropy has been gathered.
With previous versions it will continue to gather from all the above
sources since no \s-1SSL\s0 function exists to tell when enough data is
available.
.PP
Note that on Windows machines that do not have console user
interaction (mouse movements, creating windows, etc) the screen
contents are not variable enough to be sufficient, and you should
provide a random file for use with the \fI\-R\fR flag.
.PP
Note that the file specified with the \fI\-R\fR flag should contain random
data -- that means it should contain different information each time
\fIstunnel\fR is run.  This is handled automatically unless the \fI\-W\fR
flag is used.  If you wish to update this file manually, the \fIopenssl
rand\fR command in recent versions of OpenSSL, would be useful.
.PP
One important note -- if /dev/urandom is available, OpenSSL has a
habit of seeding the \s-1PRNG\s0 with it even when checking the random state,
so on systems with /dev/urandom you're likely to use it even though
it's listed at the very bottom of the list above.  This isn't
stunnel's behaviour, it's OpenSSLs.
.SH "LIMITATIONS"
\fIstunnel\fR cannot be used for the FTP daemon because of the nature of
the FTP protocol which utilizes multiple ports for data transfers.
There are available SSL enabled versions of FTP and telnet daemons,
however.
.SH "SEE ALSO"
.Ip "the \fItcpd(8)\fR manpage" 4
access control facility for internet services
.Ip "the \fIinetd(8)\fR manpage" 4
internet ``super-server'\*(R'
.Ip "\fIhttp://stunnel.mirt.net/\fR" 4
Stunnel homepage
.Ip "\fIhttp://www.stunnel.org/\fR" 4
Stunnel Frequently Asked Questions
.Ip "\fIhttp://www.openssl.org/\fR" 4
OpenSSL project website
.SH "AUTHOR"
.Ip "Michal Trojnara" 4
<\fIMichal.Trojnara@mirt.net\fR>

.rn }` ''
.IX Title "STUNNEL.OUT 1"
.IX Name "stunnel - universal SSL tunnel"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "OPTIONS"

.IX Item "\fB\-h\fR"

.IX Item "\fB\-V\fR"

.IX Item "\fB\-D\fR level"

.IX Item "\fB\-O\fR a|l|r:option=value[:value]"

.IX Item "\fB\-o\fR file"

.IX Item "\fB\-C\fR cipherlist"

.IX Item "\fB\-c\fR"

.IX Item "\fB\-T\fR"

.IX Item "\fB\-p\fR pemfile"

.IX Item "\fB\-v\fR level"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\fB\-a\fR directory"

.IX Item "\fB\-A\fR certfile"

.IX Item "\fB\-S\fR sources"

.IX Item "\fB\-t\fR timeout"

.IX Item "\fB\-N\fR servicename"

.IX Item "\fB\-u\fR ident_username"

.IX Item "\fB\-n\fR proto"

.IX Item "\fB\-E\fR socket"

.IX Item "\fB\-R\fR filename"

.IX Item "\fB\-W\fR"

.IX Item "\fB\-B\fR bytes"

.IX Item "\fB\-I\fR host"

.IX Item "\fB\-d\fR [host:]port"

.IX Item "\fB\-f\fR"

.IX Item "\fB\-l\fR program [-- programname [arg1 arg2 arg3...]  ]"

.IX Item "\fB\-L\fR program [-- programname [arg1 arg2 arg3...]  ]"

.IX Item "\fB\-s\fR username"

.IX Item "\fB\-g\fR groupname"

.IX Item "\fB\-P\fR { dir/ | file | none }"

.IX Item "\fB\-r\fR [host:]port"

.IX Header "EXAMPLES"

.IX Header "CERTIFICATES"

.IX Header "RANDOMNESS"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Header "LIMITATIONS"

.IX Header "SEE ALSO"

.IX Item "the \fItcpd(8)\fR manpage"

.IX Item "the \fIinetd(8)\fR manpage"

.IX Item "\fIhttp://stunnel.mirt.net/\fR"

.IX Item "\fIhttp://www.stunnel.org/\fR"

.IX Item "\fIhttp://www.openssl.org/\fR"

.IX Header "AUTHOR"

.IX Item "Michal Trojnara"

