#!/bin/sh

# Checking if the verifyPeer option verifies the peer certificate.
# The peer certificate is stored in the file specified with CAfile.
# The success is expected because the client presents the valid certificate.

. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [client]
  client = yes
  accept = 127.0.0.1:${http1}
  connect = 127.0.0.1:${https1}
  cert = ${script_path}/certs/client_cert.pem

  [server]
  accept = 127.0.0.1:${https1}
  connect = 127.0.0.1:${http_nc}
  cert = ${script_path}/certs/server_cert.pem
  verifyPeer = yes
  CAfile = ${script_path}/certs/PeerCerts.pem
EOT
}

test_log_for "011_verify_peer" "success" "0" "$1" "$2" "$3" 2>> "stderr.log"
exit $?
