#!/bin/sh
. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [client]
  client = yes
  accept = 127.0.0.1:${http1}
  connect = 127.0.0.1:${https1}
  verifyChain = yes
  CAfile = ${script_path}/certs/CACert.pem
  CRLfile = ${script_path}/certs/CACertCRL.pem

  [server]
  accept = 127.0.0.1:${https1}
  connect = 127.0.0.1:${http_nc}
  cert = ${script_path}/certs/server_cert.pem
EOT
}

if grep -q -e "OpenSSL 0.9.8" -e "OpenSSL 1" "results.log"
  then
    test_log_for "013_CRL_file" "success" "0" "$1" "$2" "$3" 2>> "stderr.log"
    exit $?
  else # older OpenSSL doesn't support sha256
    exit_logs "013_CRL_file" "skipped"
    clean_logs
    exit 125
  fi
