#!/bin/sh
. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [https client]
  client = yes
  accept = 127.0.0.1:${http1}
  connect = 127.0.0.1:${https}
  PSKsecrets = ${script_path}/certs/psk1.txt

  [https server]
  accept = 127.0.0.1:${https}
  connect = 127.0.0.1:${http2}
  ciphers = PSK
  PSKsecrets = ${script_path}/certs/secrets.txt
EOT
}

check_ports "014_PSK_secrets"
if grep -q "OpenSSL 1" "results.log"
  then
    start 2> "error.log"
    test_log_for "014_PSK_secrets" "success" "$1" 2>> "stderr.log"
    exit $?
  else
    exit_logs "014_PSK_secrets" "skipped"
    exit 125
  fi
