#!/bin/sh
. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  log = overwrite
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [https client]
  client = yes
  accept = 127.0.0.1:${http1}
  connect = :::${https}

  [https server]
  accept = :::${https}
  connect = 127.0.0.1:${http2}
  cert = ${script_path}/certs/stunnel.pem
EOT
}

check_ports "020_IPv6"
if grep -q "IPv6" "results.log" && [ -n "$(command -v ncat)" ] # nc does not support IPv6
  then
    start 2> "error.log"
    test_log_for "020_IPv6" "success" 2>> "stderr.log"
    exit $?
  else
    screen_result "020_IPv6" "skipped"
    file_result "020_IPv6" "error" "skipped"
    exit 125
  fi
