#!/bin/sh
. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [https client]
  client = yes
  accept = 127.0.0.1:${http1}
  connect = ${https}

  [https server]
  accept = 127.0.0.1:${https}
  accept = 127.0.0.1:${https}
  connect = ${http2}
  cert = ${script_path}/certs/server_cert.pem
EOT
}

check_ports "022_bind"
start 2> "error.log"
test_log_for "022_bind" "success" "$1" 2>> "stderr.log"
exit $?
