#!/bin/sh

# Simple execute a local inetd-type program.
# The execArgs option contains arguments for exec including the program name.

. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log
  execArgs = execute 030_simple_execute

  [client]
  client = yes
  accept = 127.0.0.1:${http1}
  connect = 127.0.0.1:${https1}

  [server]
  accept = 127.0.0.1:${https1}
  exec = ${script_path}/execute
  cert = ${script_path}/certs/server_cert.pem
EOT
}

test_log_for "030_simple_execute" "execute" "0" "$1" "$2" "$3" 2>> "stderr.log"
exit $?
