#!/bin/sh
. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [https client]
  client = yes
  accept = 127.0.0.1:${http1}
  connect = 127.0.0.1:${https}
  ;cert = ${script_path}/certs/client_cert.pem
;wrong certificate
  cert = ${script_path}/certs/stunnel.pem

  [client_2]
  client = yes
  accept = 127.0.0.1:${http2}
  connect = 127.0.0.1:${https2}

  [https server]
  accept = 127.0.0.1:${https}
  exec = ${script_path}/execute
  execArgs = execute 033_redirect_exec_error
  redirect = ${http2}
  cert = ${script_path}/certs/server_cert.pem
  verifyPeer = yes
  CAfile = ${script_path}/certs/PeerCerts.pem

  [server_2]
  accept = 127.0.0.1:${https2}
  cert = ${script_path}/certs/server_cert.pem
  exec = ${script_path}/execute
  execArgs = execute 033_redirect_exec
EOT
}

check_ports "033_redirect_exec"
start 2> "error.log"
test_log_for "033_redirect_exec" "execute" "$1" 2>> "stderr.log"
exit $?
