#!/bin/sh
. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [client]
  client = yes
  failover = prio
  accept = 127.0.0.1:${http1}
  connect = 127.0.0.1:${https1}
  connect = 127.0.0.1:${https2}

  [server_1]
  accept = 127.0.0.1:${https1}
  connect = 127.0.0.1:${http_nc}
  cert = ../certs/server_cert.pem

  [server_2]
  accept = 127.0.0.1:${https2}
  connect = 127.0.0.1:${http_nc}
  cert = ../certs/server_cert.pem
EOT
}

test_log_for "037_failover_prio1" "prio" "0" "$1" "$2" "$3" 2>> "stderr.log"
exit $?
