#!/bin/sh
. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [https client]
  client = yes
  failover = rr
  accept = 127.0.0.1:${http1}
  connect = 127.0.0.1:${https}
  connect = 127.0.0.1:${https2}
  connect = 127.0.0.1:${https3}

  [https server_1]
  accept = 127.0.0.1:${https}
  connect = 127.0.0.1:${http2}
  cert = ${script_path}/certs/server_cert.pem

  [https server_2]
  accept = 127.0.0.1:${https2}
  connect = 127.0.0.1:${http2}
  cert = ${script_path}/certs/server_cert.pem

  [https server_3]
  accept = 127.0.0.1:${https3}
  connect = 127.0.0.1:${http2}
  cert = ${script_path}/certs/server_cert.pem
EOT
}

check_ports "039_failover_rr"
test_log_for "039_failover_rr" "rr" "$1" 2>> "stderr.log"
exit $?
