#!/bin/sh

# Checking if the delay option works properly when the session is resumed.
# This option delays DNS lookup for the connect option.
# Delayed resolver inflicts failover = prio.
# Just "1" "accepted: new session negotiated" log for [server_1] service is expected.

. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  delay = yes
  retry = yes

  [client]
  client = yes
  exec = ${script_path}/execute_read
  execArgs = execute_read ${result_path}/temp.log
  connect = 127.0.0.1:${https1}

  [server_1]
  accept = 127.0.0.1:${https1}
  exec = ${script_path}/execute
  execArgs = execute 043_session_delay
  cert = ${script_path}/certs/server_cert.pem
EOT
}

if ! grep -q "FORK" "results.log"
  then
    test_log_for "043_session_delay" "session" "1" "$1" "$2" "$3" 2>> "stderr.log"
    exit $?
  else # the resumption of the session does not work for the FORK model
    exit_logs "043_session_delay" "skipped"
    exit 125
  fi
exit $?
