#!/bin/sh

# Redirect TLS client connections on certificate-based authentication failures.
# [client_1] -> [server_1] -> [client_2] -> [server_2]
# The success is expected because the client doesn't present any certificate
# and the client connection is redirected.

. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [client_1]
  client = yes
  accept = 127.0.0.1:${http1}
  connect = 127.0.0.1:${https1}
;no certificate

  [client_2]
  client = yes
  accept = 127.0.0.1:${http2}
  connect = 127.0.0.1:${https2}

  [server_1]
  accept = 127.0.0.1:${https1}
  exec = ${script_path}/execute
  execArgs = execute 049_redirect_nocert_error
  redirect = 127.0.0.1:${http2}
  cert = ${script_path}/certs/server_cert.pem
  verifyPeer = yes
  CAfile = ${script_path}/certs/PeerCerts.pem

  [server_2]
  accept = 127.0.0.1:${https2}
  cert = ${script_path}/certs/server_cert.pem
  exec = ${script_path}/execute
  execArgs = execute 049_redirect_nocert
EOT
}

test_log_for "049_redirect_nocert" "execute" "0" "$1" "$2" "$3" 2>> "stderr.log"
exit $?
