#!/bin/sh

# Checking the wrong configuration.
# The failure is expected because there is no connect option in the client service.

. $(dirname $0)/../test_library

start() {
  ../../src/stunnel -fd 0 <<EOT
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [client]
  client = yes
  accept = 127.0.0.1:${http1}
  ;*** error***
  ;connect = 127.0.0.1:${https1}
  cert = ${script_path}/certs/client_cert.pem

  [server]
  accept = 127.0.0.1:${https1}
  connect = 127.0.0.1:${http_nc}
  cert = ${script_path}/certs/server_cert.pem
EOT
}

test_log_for "115_failure_wrong_config" "failure" "0" "$1" "$2" "$3" 2>> "stderr.log"
exit $?


